travis:
  secure:
    BINSTAR_TOKEN: WZh0m5c+PZAMfuxhBFVlpsB9gRf7ur3/6/ISyWzufsUoQA/Zjpl3SS+MP079WnKYZlrzxCbgAf3p7JDnIT0BLIP6RHNbRYQDgUKqrErsDZNoAX1snMYE/frxvIIu7el+siLB+QAH+1vuYfEq/vRRfOhPEeEnnKrIDtXvc0lugt8zqr5E+uGyzJ7ySa02bzjqdIVN+01eM9kXrD5IRQoHspCnmCUWvRzLpVf+iacf2p/gVHi4YPXHAJGr1wmIUSTrfyxQwlz5FTAlxF+Y5Sd7WcU8CX68w/aNvWiWCmNWkbpsoh+LbDoy7f+gRoTmqKGlqdO4LWIdFB/QQmn2VCQfmLyb/lbZOtsGVTLzIY0mgbp9ab7Mh9l1I0mDnuf2RhBTRNRCiW8MzNunT/vXkJBYDgPDR1Eltfr8ObVJO7CVCOYNapcx1Iyh8crmZvUkkjzAG7SMW2kR3BZuXlGJrv8UCD+iIr4qUd8da4nXecN6KMyB+XNif5Xmdip7FnPXUrpApILFr5DzwMUVv6NY0gNZ/OKlIoNV7aqx6gUa9S+nXtYcGr9cEQ2eIIw6JGXDD95oYqSHo/moSOFUBeJXnKeDfcQbWBC1Yc3hCGlXi/xPl1F7vne9oPHa1mby0XWyUYb0CrAs3YYWgJ2vTTEeuXB6+hmcSc0GW1KUd0MmOme8utQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
